In [1]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

In [2]:
R6df = pd.read_csv('~/OneDrive/python3/aminomap/Amyloid_prediction/amyloid_sequence_01.csv')
R6df.tail()

    Sequence  Amyloid
234   AEMEYL        0
235   AENGKS        0
236   AEVLAL        0
237   AGVNYF        1
238   AINKIQ        0

In [3]:
site=R6df["Sequence"]
site.head()

0    AAELRN
1    AARRFF
2    AEKLFD
3    AEMEYL
4    AENGKS
Name: Sequence, dtype: object

In [4]:
First=site.str[0]
Second=site.str[1]
Third=site.str[2]
Fourth=site.str[3]
Fifth=site.str[4]
Sixth=site.str[5]

In [5]:
df1=pd.DataFrame(First)
df1=df1.rename(columns={"Sequence":"First"})
df2=pd.DataFrame(Second)
df2=df2.rename(columns={"Sequence":"Second"})
df3=pd.DataFrame(Third)
df3=df3.rename(columns={"Sequence":"Third"})
df4=pd.DataFrame(Fourth)
df4=df4.rename(columns={"Sequence":"Fourth"})
df5=pd.DataFrame(Fifth)
df5=df5.rename(columns={"Sequence":"Fifth"})
df6=pd.DataFrame(Sixth)
df6=df6.rename(columns={"Sequence":"Sixth"})

In [6]:
df=pd.concat([df1,df2,df3,df4,df5,df6],axis=1)
df.head()
#column=["A","B","C","D","E","F"]

  First Second Third Fourth Fifth Sixth
0     A      A     E      L     R     N
1     A      A     R      R     F     F
2     A      E     K      L     F     D
3     A      E     M      E     Y     L
4     A      E     N      G     K     S

In [7]:
R6df = pd.concat([R6df,df],axis=1)

In [8]:
R6df.head()

  Sequence  Amyloid First Second Third Fourth Fifth Sixth
0   AAELRN        0     A      A     E      L     R     N
1   AARRFF        0     A      A     R      R     F     F
2   AEKLFD        0     A      E     K      L     F     D
3   AEMEYL        0     A      E     M      E     Y     L
4   AENGKS        0     A      E     N      G     K     S

In [9]:
R6df=R6df.reset_index()
R6df

     index Sequence  Amyloid First Second Third Fourth Fifth Sixth
0        0   AAELRN        0     A      A     E      L     R     N
1        1   AARRFF        0     A      A     R      R     F     F
2        2   AEKLFD        0     A      E     K      L     F     D
3        3   AEMEYL        0     A      E     M      E     Y     L
4        4   AENGKS        0     A      E     N      G     K     S
5        5   AEVLAL        0     A      E     V      L     A     L
6        6   AGVNYF        1     A      G     V      N     Y     F
7        7   AINKIQ        0     A      I     N      K     I     Q
8        8   ALEEYT        1     A      L     E      E     Y     T
9        9   AQFIIS        1     A      Q     F      I     I     S
10      10   ASSSNY        1     A      S     S      S     N     Y
11      11   ATVIIE        1     A      T     V      I     I     E
12      12   DADLYL        0     D      A     D      L     Y     L
13      13   DAVKIS        0     D      A     V      K     I     S
14      14   DCVNIT        1     D      C     V      N     I     T
15      15   DDSLFF        0     D      D     S      L     F     F
16      16   DECFFF        0     D      E     C      F     F     F
17      17   DIEVDL        0     D      I     E      V     D     L
18      18   DILTYT        0     D      I     L      T     Y     T
19      19   DLLKNG        0     D      L     L      K     N     G
20      20   DTVIIE        1     D      T     V      I     I     E
21      21   EALYLV        0     E      A     L      Y     L     V
22      22   ECFFFE        0     E      C     F      F     F     E
23      23   EECLFL        0     E      E     C      L     F     L
24      24   EGVLYV        1     E      G     V      L     Y     V
25      25   EHSDLS        0     E      H     S      D     L     S
26      26   EIPAGV        0     E      I     P      A     G     V
27      27   EKDEYA        0     E      K     D      E     Y     A
28      28   EKNLYL        0     E      K     N      L     Y     L
29      29   ERGFFY        0     E      R     G      F     F     Y
..     ...      ...      ...   ...    ...   ...    ...   ...   ...
209    209   VSFEIV        1     V      S     F      E     I     V
210    210   VTLSQP        0     V      T     L      S     Q     P
211    211   VTQEFW        0     V      T     Q      E     F     W
212    212   VTSTFS        1     V      T     S      T     F     S
213    213   VTVIIE        1     V      T     V      I     I     E
214    214   VYSRHP        0     V      Y     S      R     H     P
215    215   WIVIFF        1     W      I     V      I     F     F
216    216   WSFYLL        0     W      S     F      Y     L     L
217    217   WTVIIE        1     W      T     V      I     I     E
218    218   WVENYP        0     W      V     E      N     Y     P
219    219   WVFWIG        1     W      V     F      W     I     G
220    220   WYFYIQ        0     W      Y     F      Y     I     Q
221    221   YASEIE        0     Y      A     S      E     I     E
222    222   YLEIII        0     Y      L     E      I     I     I
223    223   YLNWYQ        1     Y      L     N      W     Y     Q
224    224   YQLENY        0     Y      Q     L      E     N     Y
225    225   YTFTIS        0     Y      T     F      T     I     S
226    226   YTVIIE        1     Y      T     V      I     I     E
227    227   YVEYIG        1     Y      V     E      Y     I     G
228    228   YVSGFH        0     Y      V     S      G     F     H
229    229   YYQNYQ        1     Y      Y     Q      N     Y     Q
230    230   YYTEFT        0     Y      Y     T      E     F     T
231    231   AAELRN        0     A      A     E      L     R     N
232    232   AARRFF        0     A      A     R      R     F     F
233    233   AEKLFD        0     A      E     K      L     F     D
234    234   AEMEYL        0     A      E     M      E     Y     L
235    235   AENGKS        0     A      E     N      G     K     S
236    236   AEVLAL        0     A      E     V      L     A     L
237    237   AGVNYF        1     A      G     V      N     Y     F
238    238   AINKIQ        0     A      I     N      K     I     Q

[239 rows x 9 columns]

In [13]:
AA = pd.read_csv('~/OneDrive/python3/aminomap/Amyloid_prediction/aminoacid_parameter_minmax.csv', index_col=0)
AA

   Name         0         1         2         3         4         5         6
0     A  0.305489  0.121951  0.123762  0.404908  0.405648  1.000000  0.235294
1     G  0.000000  0.000000  0.000000  0.309816  0.400513  0.000000  0.000000
2     V  0.875895  0.341463  0.371287  0.684049  0.394095  0.482759  1.000000
3     L  0.618138  0.463415  0.495050  0.831288  0.396662  0.896552  0.470588
4     I  1.000000  0.463415  0.495050  0.861963  0.396662  0.586207  0.882353
5     F  0.701671  0.707317  0.728960  0.858896  0.349166  0.586207  0.676471
6     Y  0.701671  0.731707  0.800743  0.604294  0.347882  0.413793  0.764706
7     W  0.766110  1.000000  1.000000  1.000000  0.383825  0.655172  0.794118
8     T  0.723150  0.268293  0.321782  0.389571  0.340180  0.275862  0.617647
9     S  0.312649  0.146341  0.198020  0.297546  0.353017  0.241379  0.382353
10    R  0.558473  0.707317  0.758663  0.000000  1.000000  0.793103  0.294118
11    K  0.451074  0.536585  0.590347  0.006135  0.903723  0.655172  0.352941
12    H  0.713604  0.560976  0.576733  0.349693  0.608472  0.482759  0.441176
13    D  0.381862  0.268293  0.344059  0.073620  0.000000  0.413793  0.147059
14    E  0.372315  0.365854  0.467822  0.113497  0.017972  1.000000  0.176471
15    N  0.381862  0.317073  0.365099  0.125767  0.458280  0.275862  0.205882
16    Q  0.372315  0.439024  0.488861  0.242331  0.346598  0.793103  0.294118
17    M  0.560859  0.536585  0.548267  0.687117  0.354300  0.862069  0.500000
18    P  0.637232  0.000000  0.336634  0.530675  0.494223  0.000000  0.558824
19    C  0.422434  0.317073  0.300743  0.782209  0.436457  0.137931  0.764706

In [16]:
AA=AA.rename(columns={"0":"s"})
AA=AA.rename(columns={"1":"p"})
AA=AA.rename(columns={"2":"v"})
AA=AA.rename(columns={"3":"h"})
AA=AA.rename(columns={"4":"i"})
AA=AA.rename(columns={"5":"a"})
AA=AA.rename(columns={"6":"b"})
AA

   Name         s         p         v         h         i         a         b
0     A  0.305489  0.121951  0.123762  0.404908  0.405648  1.000000  0.235294
1     G  0.000000  0.000000  0.000000  0.309816  0.400513  0.000000  0.000000
2     V  0.875895  0.341463  0.371287  0.684049  0.394095  0.482759  1.000000
3     L  0.618138  0.463415  0.495050  0.831288  0.396662  0.896552  0.470588
4     I  1.000000  0.463415  0.495050  0.861963  0.396662  0.586207  0.882353
5     F  0.701671  0.707317  0.728960  0.858896  0.349166  0.586207  0.676471
6     Y  0.701671  0.731707  0.800743  0.604294  0.347882  0.413793  0.764706
7     W  0.766110  1.000000  1.000000  1.000000  0.383825  0.655172  0.794118
8     T  0.723150  0.268293  0.321782  0.389571  0.340180  0.275862  0.617647
9     S  0.312649  0.146341  0.198020  0.297546  0.353017  0.241379  0.382353
10    R  0.558473  0.707317  0.758663  0.000000  1.000000  0.793103  0.294118
11    K  0.451074  0.536585  0.590347  0.006135  0.903723  0.655172  0.352941
12    H  0.713604  0.560976  0.576733  0.349693  0.608472  0.482759  0.441176
13    D  0.381862  0.268293  0.344059  0.073620  0.000000  0.413793  0.147059
14    E  0.372315  0.365854  0.467822  0.113497  0.017972  1.000000  0.176471
15    N  0.381862  0.317073  0.365099  0.125767  0.458280  0.275862  0.205882
16    Q  0.372315  0.439024  0.488861  0.242331  0.346598  0.793103  0.294118
17    M  0.560859  0.536585  0.548267  0.687117  0.354300  0.862069  0.500000
18    P  0.637232  0.000000  0.336634  0.530675  0.494223  0.000000  0.558824
19    C  0.422434  0.317073  0.300743  0.782209  0.436457  0.137931  0.764706

In [17]:
R6df1=pd.merge(R6df,AA,left_on="First",right_on="Name")
R6df1=R6df1.sort_values(by=["index"])
R6df2=pd.merge(R6df,AA,left_on="Second",right_on="Name")
R6df2=R6df2.sort_values(by=["index"])
R6df3=pd.merge(R6df,AA,left_on="Third",right_on="Name")
R6df3=R6df3.sort_values(by=["index"])
R6df4=pd.merge(R6df,AA,left_on="Fourth",right_on="Name")
R6df4=R6df4.sort_values(by=["index"])
R6df5=pd.merge(R6df,AA,left_on="Fifth",right_on="Name")
R6df5=R6df5.sort_values(by=["index"])
R6df6=pd.merge(R6df,AA,left_on="Sixth",right_on="Name")
R6df6=R6df6.sort_values(by=["index"])

In [18]:
R6df1

,index,Sequence,Amyloid,First,Second,Third,Fourth,Fifth,Sixth,Name,s,p,v,h,i,a,b
0,0,AAELRN,0,A,A,E,L,R,N,A,0.305489,0.121951,0.123762,0.404908,0.405648,1.000000,0.235294
1,1,AARRFF,0,A,A,R,R,F,F,A,0.305489,0.121951,0.123762,0.404908,0.405648,1.000000,0.235294
2,2,AEKLFD,0,A,E,K,L,F,D,A,0.305489,0.121951,0.123762,0.404908,0.405648,1.000000,0.235294
3,3,AEMEYL,0,A,E,M,E,Y,L,A,0.305489,0.121951,0.123762,0.404908,0.405648,1.000000,0.235294
4,4,AENGKS,0,A,E,N,G,K,S,A,0.305489,0.121951,0.123762,0.404908,0.405648,1.000000,0.235294
5,5,AEVLAL,0,A,E,V,L,A,L,A,0.305489,0.121951,0.123762,0.404908,0.405648,1.000000,0.235294
6,6,AGVNYF,1,A,G,V,N,Y,F,A,0.305489,0.121951,0.123762,0.404908,0.405648,1.000000,0.235294
7,7,AINKIQ,0,A,I,N,K,I,Q,A,0.305489,0.121951,0.123762,0.404908,0.405648,1.000000,0.235294
8,8,ALEEYT,1,A,L,E,E,Y,T,A,0.305489,0.121951,0.123762,0.404908,0.405648,1.000000,0.235294
9,9,AQFIIS,1,A,Q,F,I,I,S,A,0.305489,0.121951,0.123762,0.404908,0.405648,1.000000,0.235294
10,10,ASSSNY,1,A,S,S,S,N,Y,A,0.305489,0.121951,0.123762,0.404908,0.405648,1.000000,0.235294
11,11,ATVIIE,1,A,T,V,I,I,E,A,0.305489,0.121951,0.123762,0.404908,0.405648,1.000000,0.235294
20,12,DADLYL,0,D,A,D,L,Y,L,D,0.381862,0.268293,0.344059,0.073620,0.000000,0.413793,0.147059
21,13,DAVKIS,0,D,A,V,K,I,S,D,0.381862,0.268293,0.344059,0.073620,0.000000,0.413793,0.147059
22,14,DCVNIT,1,D,C,V,N,I,T,D,0.381862,0.268293,0.344059,0.073620,0.000000,0.413793,0.147059
23,15,DDSLFF,0,D,D,S,L,F,F,D,0.381862,0.268293,0.344059,0.073620,0.000000,0.413793,0.147059
24,16,DECFFF,0,D,E,C,F,F,F,D,0.381862,0.268293,0.344059,0.073620,0.000000,0.413793,0.147059
25,17,DIEVDL,0,D,I,E,V,D,L,D,0.381862,0.268293,0.344059,0.073620,0.000000,0.413793,0.147059
26,18,DILTYT,0,D,I,L,T,Y,T,D,0.381862,0.268293,0.344059,0.073620,0.000000,0.413793,0.147059
27,19,DLLKNG,0,D,L,L,K,N,G,D,0.381862,0.268293,0.344059,0.073620,0.000000,0.413793,0.147059
28,20,DTVIIE,1,D,T,V,I,I,E,D,0.381862,0.268293,0.344059,0.073620,0.000000,0.413793,0.147059
29,21,EALYLV,0,E,A,L,Y,L,V,E,0.372315,0.365854,0.467822,0.113497,0.017972,1.000000,0.176471
30,22,ECFFFE,0,E,C,F,F,F,E,E,0.372315,0.365854,0.467822,0.113497,0.017972,1.000000,0.176471
31,23,EECLFL,0,E,E,C,L,F,L,E,0.372315,0.365854,0.467822,0.113497,0.017972,1.000000,0.176471
32,24,EGVLYV,1,E,G,V,L,Y,V,E,0.372315,0.365854,0.467822,0.113497,0.017972,1.000000,0.176471
33,25,EHSDLS,0,E,H,S,D,L,S,E,0.372315,0.365854,0.467822,0.113497,0.017972,1.000000,0.176471
34,26,EIPAGV,0,E,I,P,A,G,V,E,0.372315,0.365854,0.467822,0.113497,0.017972,1.000000,0.176471
35,27,EKDEYA,0,E,K,D,E,Y,A,E,0.372315,0.365854,0.467822,0.113497,0.017972,1.000000,0.176471
36,28,EKNLYL,0,E,K,N,L,Y,L,E,0.372315,0.365854,0.467822,0.113497,0.017972,1.000000,0.176471
37,29,ERGFFY,0,E,R,G,F,F,Y,E,0.372315,0.365854,0.467822,0.113497,0.017972,1.000000,0.176471
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
217,209,VSFEIV,1,V,S,F,E,I,V,V,0.875895,0.341463,0.371287,0.684049,0.394095,0.482759,1.000000
218,210,VTLSQP,0,V,T,L,S,Q,P,V,0.875895,0.341463,0.371287,0.684049,0.394095,0.482759,1.000000
219,211,VTQEFW,0,V,T,Q,E,F,W,V,0.875895,0.341463,0.371287,0.684049,0.394095,0.482759,1.000000
220,212,VTSTFS,1,V,T,S,T,F,S,V,0.875895,0.341463,0.371287,0.684049,0.394095,0.482759,1.000000
221,213,VTVIIE,1,V,T,V,I,I,E,V,0.875895,0.341463,0.371287,0.684049,0.394095,0.482759,1.000000
222,214,VYSRHP,0,V,Y,S,R,H,P,V,0.875895,0.341463,0.371287,0.684049,0.394095,0.482759,1.000000
223,215,WIVIFF,1,W,I,V,I,F,F,W,0.766110,1.000000,1.000000,1.000000,0.383825,0.655172,0.794118
224,216,WSFYLL,0,W,S,F,Y,L,L,W,0.766110,1.000000,1.000000,1.000000,0.383825,0.655172,0.794118
225,217,WTVIIE,1,W,T,V,I,I,E,W,0.766110,1.000000,1.000000,1.000000,0.383825,0.655172,0.794118
226,218,WVENYP,0,W,V,E,N,Y,P,W,0.766110,1.000000,1.000000,1.000000,0.383825,0.655172,0.794118
227,219,WVFWIG,1,W,V,F,W,I,G,W,0.766110,1.000000,1.000000,1.000000,0.383825,0.655172,0.794118
228,220,WYFYIQ,0,W,Y,F,Y,I,Q,W,0.766110,1.000000,1.000000,1.000000,0.383825,0.655172,0.794118
229,221,YASEIE,0,Y,A,S,E,I,E,Y,0.701671,0.731707,0.800743,0.604294,0.347882,0.413793,0.764706
230,222,YLEIII,0,Y,L,E,I,I,I,Y,0.701671,0.731707,0.800743,0.604294,0.347882,0.413793,0.764706
231,223,YLNWYQ,1,Y,L,N,W,Y,Q,Y,0.701671,0.731707,0.800743,0.604294,0.347882,0.413793,0.764706
232,224,YQLENY,0,Y,Q,L,E,N,Y,Y,0.701671,0.731707,0.800743,0.604294,0.347882,0.413793,0.764706
233,225,YTFTIS,0,Y,T,F,T,I,S,Y,0.701671,0.731707,0.800743,0.604294,0.347882,0.413793,0.764706
234,226,YTVIIE,1,Y,T,V,I,I,E,Y,0.701671,0.731707,0.800743,0.604294,0.347882,0.413793,0.764706
235,227,YVEYIG,1,Y,V,E,Y,I,G,Y,0.701671,0.731707,0.800743,0.604294,0.347882,0.413793,0.764706
236,228,YVSGFH,0,Y,V,S,G,F,H,Y,0.701671,0.731707,0.800743,0.604294,0.347882,0.413793,0.764706
237,229,YYQNYQ,1,Y,Y,Q,N,Y,Q,Y,0.701671,0.731707,0.800743,0.604294,0.347882,0.413793,0.764706
238,230,YYTEFT,0,Y,Y,T,E,F,T,Y,0.701671,0.731707,0.800743,0.604294,0.347882,0.413793,0.764706
12,231,AAELRN,0,A,A,E,L,R,N,A,0.305489,0.121951,0.123762,0.404908,0.405648,1.000000,0.235294
13,232,AARRFF,0,A,A,R,R,F,F,A,0.305489,0.121951,0.123762,0.404908,0.405648,1.000000,0.235294
14,233,AEKLFD,0,A,E,K,L,F,D,A,0.305489,0.121951,0.123762,0.404908,0.405648,1.000000,0.235294
15,234,AEMEYL,0,A,E,M,E,Y,L,A,0.305489,0.121951,0.123762,0.404908,0.405648,1.000000,0.235294
16,235,AENGKS,0,A,E,N,G,K,S,A,0.305489,0.121951,0.123762,0.404908,0.405648,1.000000,0.235294
17,236,AEVLAL,0,A,E,V,L,A,L,A,0.305489,0.121951,0.123762,0.404908,0.405648,1.000000,0.235294
18,237,AGVNYF,1,A,G,V,N,Y,F,A,0.305489,0.121951,0.123762,0.404908,0.405648,1.000000,0.235294
19,238,AINKIQ,0,A,I,N,K,I,Q,A,0.305489,0.121951,0.123762,0.404908,0.405648,1.000000,0.235294

In [19]:
R6df1.to_csv("~/OneDrive/python3/aminomap/Amyloid_prediction/First_n.csv")

In [20]:
R6df2.shape

(239, 17)

In [21]:
R6df2.to_csv("~/OneDrive/python3/aminomap/Amyloid_prediction/Second_n.csv")
R6df3.to_csv("~/OneDrive/python3/aminomap/Amyloid_prediction/Third_n.csv")
R6df4.to_csv("~/OneDrive/python3/aminomap/Amyloid_prediction/Fourth_n.csv")
R6df5.to_csv("~/OneDrive/python3/aminomap/Amyloid_prediction/Fifth_n.csv")
R6df6.to_csv("~/OneDrive/python3/aminomap/Amyloid_prediction/Sixth_n.csv")

In [22]:
R6df2.head()

,index,Sequence,Amyloid,First,Second,Third,Fourth,Fifth,Sixth,Name,s,p,v,h,i,a,b
0,0,AAELRN,0,A,A,E,L,R,N,A,0.305489,0.121951,0.123762,0.404908,0.405648,1.0,0.235294
1,1,AARRFF,0,A,A,R,R,F,F,A,0.305489,0.121951,0.123762,0.404908,0.405648,1.0,0.235294
19,2,AEKLFD,0,A,E,K,L,F,D,E,0.372315,0.365854,0.467822,0.113497,0.017972,1.0,0.176471
20,3,AEMEYL,0,A,E,M,E,Y,L,E,0.372315,0.365854,0.467822,0.113497,0.017972,1.0,0.176471
21,4,AENGKS,0,A,E,N,G,K,S,E,0.372315,0.365854,0.467822,0.113497,0.017972,1.0,0.176471

In [23]:
First_para=R6df1.drop(columns=["Sequence","Amyloid","First","Second","Third","Fourth","Fifth","Sixth","Name"], axis=1)
Second_para=R6df2.drop(columns=["Sequence","Amyloid","First","Second","Third","Fourth","Fifth","Sixth","Name"], axis=1)
Third_para=R6df3.drop(columns=["Sequence","Amyloid","First","Second","Third","Fourth","Fifth","Sixth","Name"], axis=1)
Fourth_para=R6df4.drop(columns=["Sequence","Amyloid","First","Second","Third","Fourth","Fifth","Sixth","Name"], axis=1)
Fifth_para=R6df5.drop(columns=["Sequence","Amyloid","First","Second","Third","Fourth","Fifth","Sixth","Name"], axis=1)
Sixth_para=R6df6.drop(columns=["Sequence","Amyloid","First","Second","Third","Fourth","Fifth","Sixth","Name"], axis=1)

In [24]:
First_para.to_csv("~/OneDrive/python3/aminomap/Amyloid_prediction/First_para_n.csv")
Second_para.to_csv("~/OneDrive/python3/aminomap/Amyloid_prediction/Second_para_n.csv")
Third_para.to_csv("~/OneDrive/python3/aminomap/Amyloid_prediction/Third_para_n.csv")
Fourth_para.to_csv("~/OneDrive/python3/aminomap/Amyloid_prediction/Fourth_para_n.csv")
Fifth_para.to_csv("~/OneDrive/python3/aminomap/Amyloid_prediction/Fifth_para_n.csv")
Sixth_para.to_csv("~/OneDrive/python3/aminomap/Amyloid_prediction/Sixth_para_n.csv")

In [26]:
First_para.head()

   index         s         p         v         h         i    a         b
0      0  0.305489  0.121951  0.123762  0.404908  0.405648  1.0  0.235294
1      1  0.305489  0.121951  0.123762  0.404908  0.405648  1.0  0.235294
2      2  0.305489  0.121951  0.123762  0.404908  0.405648  1.0  0.235294
3      3  0.305489  0.121951  0.123762  0.404908  0.405648  1.0  0.235294
4      4  0.305489  0.121951  0.123762  0.404908  0.405648  1.0  0.235294

In [27]:
corr([R6df1]="Steric parameter", [R6df2]="Steric parameter")

SyntaxError: keyword can't be an expression (<ipython-input-27-3739f94305ff>, line 1)

In [28]:
R6df1.head()

,index,Sequence,Amyloid,First,Second,Third,Fourth,Fifth,Sixth,Name,s,p,v,h,i,a,b
0,0,AAELRN,0,A,A,E,L,R,N,A,0.305489,0.121951,0.123762,0.404908,0.405648,1.0,0.235294
1,1,AARRFF,0,A,A,R,R,F,F,A,0.305489,0.121951,0.123762,0.404908,0.405648,1.0,0.235294
2,2,AEKLFD,0,A,E,K,L,F,D,A,0.305489,0.121951,0.123762,0.404908,0.405648,1.0,0.235294
3,3,AEMEYL,0,A,E,M,E,Y,L,A,0.305489,0.121951,0.123762,0.404908,0.405648,1.0,0.235294
4,4,AENGKS,0,A,E,N,G,K,S,A,0.305489,0.121951,0.123762,0.404908,0.405648,1.0,0.235294

In [29]:
Second_para.head()

    index         s         p         v         h         i    a         b
0       0  0.305489  0.121951  0.123762  0.404908  0.405648  1.0  0.235294
1       1  0.305489  0.121951  0.123762  0.404908  0.405648  1.0  0.235294
19      2  0.372315  0.365854  0.467822  0.113497  0.017972  1.0  0.176471
20      3  0.372315  0.365854  0.467822  0.113497  0.017972  1.0  0.176471
21      4  0.372315  0.365854  0.467822  0.113497  0.017972  1.0  0.176471

In [153]:
FIRST=[1,0,0,0,0,0,0]
SECOND=[0,1,0,0,0,0,0]
THIRD=[0,0,1,0,0,0,0]
FOURTH=[0,0,0,1,0,0,0]
FIFTH=[0,0,0,0,0,1,0]
SIXTH=[0,0,0,0,0,0,1]

FIRST_p0=[1.28,0.05,1.0,0.31,6.11,0.42,0.23]
SECOND_p0=Second_para.loc[:0,["s","p","v","h","i","a","b"]]
THIRD_p0=_para.loc[:0,["s","p","v","h","i","a","b"]]

FIRSTdf=pd.DataFrame(FIRST)
SECONDdf=pd.DataFrame(SECOND)
FIRST_p0df=pd.DataFrame(FIRST_p0)
SECOND_p0df=pd.DataFrame(SECOND_p0)

FIRST_p0dfT=FIRST_p0df.T
SECOND_p0dfT=SECOND_p0df.T

In [159]:
A=np.dot(FIRSTdf,FIRST_p0dfT)

In [160]:
B=np.dot(SECONDdf,SECOND_p0df)

In [163]:
A+B

array([[1.28, 0.05, 1.  , 0.31, 6.11, 0.42, 0.23],
       [1.28, 0.05, 1.  , 0.31, 6.11, 0.42, 0.23],
       [0.  , 0.  , 0.  , 0.  , 0.  , 0.  , 0.  ],
       [0.  , 0.  , 0.  , 0.  , 0.  , 0.  , 0.  ],
       [0.  , 0.  , 0.  , 0.  , 0.  , 0.  , 0.  ],
       [0.  , 0.  , 0.  , 0.  , 0.  , 0.  , 0.  ],
       [0.  , 0.  , 0.  , 0.  , 0.  , 0.  , 0.  ]])

In [148]:
SECOND_p0

      s     p    v     h     i     a     b
0  1.28  0.05  1.0  0.31  6.11  0.42  0.23

In [141]:
SECOND_p0df

      s     p    v     h     i     a     b
0  1.28  0.05  1.0  0.31  6.11  0.42  0.23

In [119]:
FIRST

[1, 0, 0, 0, 0, 0, 0]

In [150]:
FIRSTdf

   0
0  0
1  1
2  0
3  0
4  0
5  0
6  0

In [120]:
FIRST_p0df

      0
0  1.28
1  0.05
2  1.00
3  0.31
4  6.11
5  0.42
6  0.23

In [121]:
FIRST_p0dfT

      0     1    2     3     4     5     6
0  1.28  0.05  1.0  0.31  6.11  0.42  0.23